### ISSUE TITLE
configure a Multiline codec

### ISSUE THREAD

**Issue by salvadorsm** [Cimpress-MCP/TimberWinR#23]
I have configured a Multiline codec in Logstash, so I can join all the multiline logs in only one line.

Can we do it for TimberWinR?

This is what I have now in Logsstash and it is working:

input { 
file {
  type => "Logs"
  path => "C:/Users/******/Documents/Test/log/Test.log"
  codec => multiline {
pattern => "(^(?!\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3}.*$))"
what => "previous"
	}
}

Thanks in advance!

Salvador.-

**Comment by efontana** [comment]
Can you post a few lines from your log file (at least 2 complete multiline messages) so I can use to test.

**Comment by salvadorsm** [comment]
2015-01-07 13:14:26,572 TEST DEBUG [THREAD : 25] - Sending message to TServer - tcp://10.1111.11.111:1111
'RequestAttachUserData' ('30')
message attributes:
AttributeConnID [long] = 00890
AttributeReferenceID [int] = 88
AttributeThisDN [str] = "2214"
AttributeUserData [bstr] = KVList: 
		'ActivityID' [str] = "1-XXXXXX"
2015-01-07 13:14:26,574 TEST DEBUG [THREAD : 25] - Writing message RequestAttachUserData in 'proxy1' via '.StatePrimary proxy: proxy1'
2015-01-07 13:14:26,575 TEST DEBUG [THREAD : 25] - sending RequestAttachUserData to Test.Platform.Commons.Connection.CommonConnection
2015-01-07 13:20:31,665 TEST DEBUG [THREAD : SelectorThread] - Proxy got message 'EventOnHook' ('87')
message attributes:
AttributeEventSequenceNumber [long] = 4899493
Time            = ComplexClass(TimeStamp):
	AttributeTimeinuSecs [int] = 573000
	AttributeTimeinSecs [int] = 1420644031
AttributeThisDN [str] = "2214"
. Processing with  state .StatePrimary proxy: proxy1

**Comment by efontana** [comment]
Your regular expression seems wonky to me, especially the first part? the '?!' This seems 
more like what it should be?

    ^(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3})(.*)$

If I interpret this correctly, the first line is the one with the date, and the subsequent lines (non-date matched) are appended to the first line.   Can you confirm?

**Comment by salvadorsm** [comment]
You're right.
However, my REGEX is OK, since ?! is negating the complete expression.
What Logstash does is search for a match of a line (everything not containing a date) and append that to the previous valid entry (line starting with a date).

**Comment by efontana** [comment]
Added support for Multiline codec in commit:

https://github.com/Cimpress-MCP/TimberWinR/commit/dec51efccdeda48545753d8a6763338a9245ddeb
