### ISSUE TITLE
Multiline filter

### ISSUE THREAD

**Issue by jsosic** [Cimpress-MCP/TimberWinR#24]
Hi,

TimberWinR doesn't support multiline filter, which is a big problem if you want to parse/ship Java or .NET exception logs.

How big of a problem is to implement it?

**Comment by efontana** [comment]
It was just implemented check the docs

**Comment by jsosic** [comment]
Ah you're the man, sorry that I missed it! Are there new MSI packages available out there?

**Comment by jsosic** [comment]
OK I see multiline codec doesn't support negate option for pattern match, so I will edit this bug to reflect on that one.
