### ISSUE TITLE
Multiline codec doesn't support negate option for pattern matching

### ISSUE THREAD

**Issue by jsosic** [Cimpress-MCP/TimberWinR#25]
Hi,

Logstash multiline filter has param "negate", which is by default false, and if true pattern match is inverted (negation is applied). This helps if we know how the FIRST line of the log starts, and if we can't anticipate all the possible line starts/matches for the next lines in multiline log entry.

For example, in logstash, one could attach all log lines to previos log entry if the lines don't start with timestamp, and this is by far the most widely used pattern:

```
multiline {
  patter => "%{TIMESTAMP_ISO8601}
  negate => true
  what => previous
}
```

If you could add support for negating patter, that would be awesome. Thank you!

**Comment by jsosic** [comment]
I think the workaround for this one can be negative lookahead regex pattern. For example if you match line looking like:

```
2015-01-16 10:06:43,546
```

Regex would be:
```
"^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})"
```

So, if we want to match all lines that are not staring with that, we could use negative lookahead:

```
"^(?!([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})).*"
```

**Comment by efontana** [comment]
Negate is supported

**Comment by efontana** [comment]
The doc just needed updating.
