### ISSUE TITLE
Allow options to be specified as objects rather than arrays

### ISSUE THREAD

**Issue by ryanbreen** [Cimpress-MCP/TimberWinR#27]
It seems like it would be cleaner to create something like a set of mutators as an object rather than an array.

For example, instead of:

```json
  "Filters": [     
    {
		"mutate": {      			
			"rename": [
				"ComputerName", "Host",
				"host", "Host",
				"message","Message",
				"type","Type",
				"SID", "Username"                 
			]
		}                
    }     
  ]
```

We could do:

```json
  "Filters": [     
    {
		"mutate": {      			
			"rename": {
				"ComputerName": "Host",
				"host": "Host",
				"message": "Message",
				"type": "Type",
				"SID": "Username"                 
			}
		}                
    }     
  ]
```

It should be possible to add that in a backwards compatible way, and that feels like a more JSONy way of doing things than matched pairs in an array.

**Comment by efontana** [comment]
I had originally done it that way, logstash does it this way, so I was trying to make it easy, they do it with an array of pairs.  http://logstash.net/docs/1.4.2/filters/mutate#rename
