### ISSUE TITLE
Add option to avoid sending logs to failing target

### ISSUE THREAD

**Issue by siewers** [Cimpress-MCP/TimberWinR#28]
I've just experienced an issue with my Elasticsearch instance going down, causing the log messages in this period to get lost.
For a period of about 10 minutes, no logs could be shipped to the Elasticsearch instance, but TimberWinR still tried to send them, causing them to get dropped.

It would be a great enhancement to be able to configure whether the logs should be dropped or not, in case the target is not available.

**Comment by efontana** [comment]
This is resolved by using maxQueueSize and overflowDiscardOldest parameters for the Elasticsearch output.
