### ISSUE TITLE
Any easy way to count matches lines and basic aggregations with TimberWinR

### ISSUE THREAD

**Issue by toni-moreno** [Cimpress-MCP/TimberWinR#36]
Hi.

I'm looking for a windows tool with can read log files and count events based on regex and also do basic aggregation operations ( sum/ avg / max / min ) by interval, by example one minute. ( the same behavior than does the plugin tail in collectd tool for unix systems https://collectd.org/wiki/index.php/Plugin:Tail ).

There is any way to add this feature to the TimberWinR tool?

Thank you very much

**Comment by thoean** [comment]
Is TimberWinR the correct tool to do this? Don't you actually want a CollectD output filter and leave the job to CollectD (or Elasticsearch since that's already supported)? I understand TimberWinR as a pure forwarder to tools that are built for aggregation and visualization.

**Comment by toni-moreno** [comment]
Hi @thoean. I'm working with Graphite as a metric backend, and working with a resolution of 1 sample data per minute.

I'm looking for one  windows standalone tool  like linux collectd ( with tail plugin and graphite_output plugin ) to count log files that matches a regex and do max/min/average for some numbers got from these log files.

The first approach is a event parser and a aggregation back-end as you suggested.

(logstash + statsd -> graphite).

But this approach  cause heavy load on network and needs for the maintenance of another  extra tool ( statsd).

WimberWinR could not be the main goal for this tool , but I think , could be modified to add a Graphite output backend. ( https://github.com/ragnard/Graphite.NET ) and a way to add counters and send one sample per period ( 1 minute in my case)

**Comment by efontana** [comment]
Sounds like we need a Statsd outputter and a Metrics filter.

**Comment by toni-moreno** [comment]
@efontana , yes we need !!! 

If done  I would like to be your beta tester for this kind of  filter and output.
