### ISSUE TITLE
Support for adding tags or setting input type

### ISSUE THREAD

**Issue by genebean** [Cimpress-MCP/TimberWinR#49]
I do all my grok'ing on the central server based on type and / tags. Unless I am missing it, I don't see a way to add a tag via an input nor do I see a way to set the type.  For example, on a Linux host I have the following input:

```
input {
  file {
    type    => "zabbix-server"
    path    => [ "/var/log/zabbix/zabbix_agentd.log" ]
  }
}
```

I then have the following filter on my indexer:

```
filter {
  if [type] == "zabbix-server" {
    grok {
      match => ["message", "%{INT:zabpid}:%{BASE16NUM:zabdate}:%{BASE16FLOAT:zabtime} item \[%{DATA:zabhost}:%{DATA:zabkey}\[%{DATA:zabparam}\]\] %{GREEDYDATA:zabmsg}"]
      match => ["message", "%{INT:zabpid}:%{BASE16NUM:zabdate}:%{BASE16FLOAT:zabtime} item \[%{DATA:zabhost}:%{DATA:zabkey}\] %{GREEDYDATA:zabmsg}"]
      match => ["message", "%{INT:zabpid}:%{BASE16NUM:zabdate}:%{BASE16FLOAT:zabtime} %{GREEDYDATA:zabmsg}" ]
    }

    mutate {
      rename => ["host", "logsource"]
      replace => ["message", "%{zabmsg}"]
      replace => ["timestamp", "%{zabdate} %{zabtime}" ]
    }
  }
}
```

I would like to be able to setup a similar input on my Windows hosts.  For what it's worth, I am even happy to help write this functionality if you can just point me in the right direction. I have written c# code before but never anything for LogStash or the like.

**Comment by efontana** [comment]
Something like this will suffice.

{
    "TimberWinR": {
        "Inputs": {
            "Logs": [
                {
                    "location": "d:\\logs\\dev\\*.log",
                    "logSource": "dev"
                },
                {
                    "location": "d:\\logs\\sta\\*.log",
                    "logSource": "sta"
                }
            ]
        },
        "Filters": [
            {
                "jsonFilters": [
                    {
                        "type": "Win32-FileLog",
                        "condition": "\"[logSource]\" == \"dev\"",
                        "source": "Text",
                        "add_field": [
                            "_index",
                            "dev-%{yyyy.MM.dd}"
                        ]
                    },
                    {
                        "type": "Win32-FileLog",
                        "condition": "\"[logSource]\" == \"sta\"",
                        "source": "Text",
                        "add_field": [
                            "_index",
                            "sta-%{yyyy.MM.dd}"
                        ]
                    }
                ]
            }
        ],
        "Outputs": {
            "StdOut": [
                {
                    "_comment": "Console"
                }
            ]
        }
    }
}

**Comment by genebean** [comment]
I'm sure I am missing something, but how does this help me apply filter on the central server? Does it add something to the tags or set the type in a way that gets included with the json going to the output?

**Comment by genebean** [comment]
I have tried every combo I can think of including looking at [GrokFilter.md](https://github.com/Cimpress-MCP/TimberWinR/blob/fd67c271b57266857db904a39db37cbb12d37671/TimberWinR/mdocs/GrokFilter.md) and can't make it work. The example below actually throws the error

```powershell
2015-04-28 15:34:14.2816|ERROR|TimberWinR.Configuration|TimberWinR.Parser.Grok+GrokAddTagException: Grok filter add_tag
requires tuples
   at TimberWinR.Parser.Grok.Validate()
   at TimberWinR.Configuration.Validate(Configuration c)
2015-04-28 15:34:14.2972|ERROR|TimberWinR.Manager|TimberWinR.Parser.Grok+GrokAddTagException: Grok filter add_tag requir
es tuples
   at TimberWinR.Configuration.Validate(Configuration c)
   at TimberWinR.Configuration.FromString(String json, Configuration c)
   at TimberWinR.Manager..ctor(String jsonConfigFile, String logLevel, String logfileDir, Boolean liveMonitor, Cancellat
ionToken cancelToken, Boolean processConfiguration)
```

Can you please help me understand how to modify this to work? Ideally, instead of matching the message I would match on the the type (Win32-Eventlog or maybe whatever TailFiles comes over as) or the source (Application or System).

```
{
    "TimberWinR": {
        "Inputs": {
            "WindowsEvents": [
                {
                    "source": "Application,System",
                    "binaryFormat": "PRINT",
                    "resolveSIDS": true
                }
            ]
        },
		"Filters": [     
			{
			   "grok": {
				   "match": [
					   "message",
					   ""
				   ],
				   "add_tag": [ "test_tag" ]
				}           
			}     
		],
		"Outputs": {
			"Redis": [
				{
					"_comment": "Change the host to your Redis instance",
					"port": 6380,
					"host": [
						"logstash.example.com"
					]
				}
			]
		}
    }
}

```

**Comment by efontana** [comment]
I am going to add a type parameter to the inputs, so it can be used on the filter.

**Comment by genebean** [comment]
Thank you very much! That "type parameter" will be part of the output too so that it will be usable as part of a filter on a remote LogStash server too, right?
